project:
  type: book
  output-dir: _book

book:
  title: "Introduction to Applied High-throughput Biological Data Analysis"
  author: "Ang Dong"
  repo-url: https://github.com/cxzdsa2332/Applied-Omics-Analysis
  repo-actions: [edit, issue, source]
  chapters:
    - index.qmd
    - part: "第一阶段：基础与基因组"
      chapters:
        - 01-intro.qmd
        - intro_lesson1.qmd
        - intro_lesson2.qmd
        - intro_lesson3.qmd
        - intro_lesson4.qmd
        - intro_lesson5.qmd
        - 02-genomics-qc.qmd
        - genomics_qc_lesson1.qmd
        - genomics_qc_lesson2.qmd
        - genomics_qc_lesson3.qmd
        - genomics_qc_lesson4.qmd
        - genomics_qc_lesson5.qmd
        - 03-genomics-variant.qmd
        - genomics_variant_lesson1.qmd
        - genomics_variant_lesson2.qmd
        - genomics_variant_lesson3.qmd
        - genomics_variant_lesson4.qmd
        - genomics_variant_lesson5.qmd
    - part: "第二阶段：转录组与单细胞"
      chapters:
        - 04-transcriptomics-basic.qmd
        - transcriptomics_basic_lesson1.qmd
        - transcriptomics_basic_lesson2.qmd
        - transcriptomics_basic_lesson3.qmd
        - transcriptomics_basic_lesson4.qmd
        - transcriptomics_basic_lesson5.qmd
        - 05-transcriptomics-advanced.qmd
        - transcriptomics_adv_lesson1.qmd
        - transcriptomics_adv_lesson2.qmd
        - transcriptomics_adv_lesson3.qmd
        - transcriptomics_adv_lesson4.qmd
        - transcriptomics_adv_lesson5.qmd
        - 06-scrna-basic.qmd
        - scrna_basic_lesson1.qmd
        - scrna_basic_lesson2.qmd
        - scrna_basic_lesson3.qmd
        - scrna_basic_lesson4.qmd
        - scrna_basic_lesson5.qmd
        - 07-scrna-advanced.qmd
        - scrna_adv_lesson1.qmd
        - scrna_adv_lesson2.qmd
        - scrna_adv_lesson3.qmd
        - scrna_adv_lesson4.qmd
        - scrna_adv_lesson5.qmd
    - part: "第三阶段：进阶与整合"
      chapters:
        - 08-epigenomics.qmd
        - epigenomics_lesson1.qmd
        - epigenomics_lesson2.qmd
        - epigenomics_lesson3.qmd
        - epigenomics_lesson4.qmd
        - epigenomics_lesson5.qmd
        - 09-proteometab.qmd
        - proteometab_lesson1.qmd
        - proteometab_lesson2.qmd
        - proteometab_lesson3.qmd
        - proteometab_lesson4.qmd
        - proteometab_lesson5.qmd
        - 10-integration.qmd
        - integration_lesson1.qmd
        - integration_lesson2.qmd
        - integration_lesson3.qmd
        - integration_lesson4.qmd
        - integration_lesson5.qmd
        - 11-summary.qmd
        - summary_lesson1.qmd
    - references.qmd

format:
  html:
    theme: flatly
    code-fold: true
    toc: true
    number-sections: true
