---
title: "Course Introduction"
number-sections: false
---

# Course Introduction {.unnumbered .unlisted}

Next-Generation Sequencing (NGS) has become the cornerstone of modern biology. This course is designed for applied high-throughput biological data analysis, covering genome assembly and variant calling, bulk RNA-seq, single-cell RNA-seq, spatial transcriptomics, 16S/ITS amplicon and shotgun metagenomics, epigenomics, proteomics and metabolomics. For each data modality, the processes of data acquisition and preprocessing are introduced in detail. The curriculum covers routine analytical methods, such as PCA and Differential Expression Gene (DEG) analysis, alongside advanced techniques like WGCNA and SCENIC. To emphasize hands-on practice, R and Python scripts are provided for half of the course modules to guide students through each workflow. Finally, beyond traditional methodologies, the concluding section introduces novel computational approaches, including ODE-based network modeling.
