project:
  type: book
  output-dir: _book

book:
  title: "Introduction to Applied High-throughput Biological Data Analysis"
  author: "Ang Dong"
  repo-url: https://github.com/cxzdsa2332/Applied-Omics-Analysis
  repo-actions: [edit, issue, source]
  chapters:
    - index.qmd
    - part: "第一阶段：基础与基因组"
      chapters:
        - 01-intro.qmd
        - 02-genomics-qc.qmd
        - 03-genomics-variant.qmd
    - part: "第二阶段：转录组与单细胞"
      chapters:
        - 04-transcriptomics-basic.qmd
        - 05-transcriptomics-advanced.qmd
        - 06-scrna-basic.qmd
        - 07-scrna-advanced.qmd
    - part: "第三阶段：进阶与整合"
      chapters:
        - 08-epigenomics.qmd
        - 09-proteometab.qmd
        - 10-integration.qmd
        - 11-summary.qmd

format:
  html:
    theme: flatly
    code-fold: true
    toc: true