{
  "hash": "f76be635b7d63d4b17aab01d5f8aea5b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Splice-Aware 比对与表达量定量\"\ndate: today\nformat:\n  html:\n    code-fold: false\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    theme: cosmo\ncrossref:\n  fig-title: 图\n  fig-prefix: 图\n  tbl-title: 表\n  tbl-prefix: 表\n  chapters: false\n---\n\n## 学习目标\n\n完成本专题后，学生应能够：\n\n1. 解释 splice-aware 比对的必要性，描述 STAR 两步比对策略的核心逻辑；\n2. 理解 GTF 注释文件中 gene_id、transcript_id、exon 的层级关系；\n3. 使用 STAR 完成 RNA-seq 双端比对，正确设置链特异性参数；\n4. 区分 featureCounts（比对后计数）与 Salmon（伪比对）的方法论差异，并在实际项目中做出合理选择；\n5. 使用 tximport 将 Salmon 转录本级别定量汇总至基因级别；\n6. 理解 TPM、FPKM 与原始计数的计算公式与适用场景，解释 DESeq2 必须使用原始计数的原因。\n\n---\n\n## 为什么 RNA-seq 比对需要特殊处理？\n\n### Read-through 与剪接位点的挑战\n\n在 DNA 测序中，read 是基因组连续区域的测序结果，比对工具只需在基因组上找到一段连续的最优匹配即可。RNA-seq 则面临根本性的不同：成熟 mRNA 经过剪接，内含子已被去除。当一个 150 bp 的 read 跨越剪接位点时，它实际上对应基因组上**两段不连续的外显子区域**，中间隔着长达数千甚至数万 bp 的内含子。\n\n若使用普通的 DNA 比对工具（如 Bowtie2），跨剪接位点的读段将无法被正确比对，或被强制比对到错误位置，导致：\n\n- Junction read（约占 20–30% 的 reads）丢失，降低定量精度；\n- 新型剪接位点无法被发现；\n- 外显子边界附近的覆盖度出现人为缺口。\n\n![RNA 剪接过程示意图。pre-mRNA 中的内含子经剪接体切除，外显子拼接为成熟 mRNA。来源：Wikipedia, RNA splicing。](https://upload.wikimedia.org/wikipedia/commons/2/24/RNA_splicing_reaction.svg){#fig-rna-splicing width=85%}\n\n### Splice-Aware 比对的解决思路\n\n普通 DNA 比对工具与 splice-aware 工具在处理跨剪接位点读段时的行为差异，可通过 @fig-splice-aware 直观说明：\n\n\n::: {.cell}\n::: {.cell-output-display}\n![普通比对工具 vs Splice-Aware 比对工具对 Junction Read 的处理差异。上方为基因组结构（外显子-内含子-外显子），中间为来自 mRNA 的 junction read（横跨剪接位点），下方对比两种比对结果。](transcriptomics_basic_lesson2_files/figure-html/fig-splice-aware-1.png){#fig-splice-aware width=960}\n:::\n:::\n\n\n@fig-splice-aware 展示了三个层次：**基因组结构**（外显子-内含子-外显子）、**普通比对（Bowtie2）** 的失败结果，以及 **Splice-Aware 比对（STAR/HISAT2）** 的正确分段比对。Junction read 来自 mRNA，其两端分别对应基因组上两个不连续的外显子；普通工具无法在基因组上找到完整的连续匹配而失败，splice-aware 工具则识别出剪接信号，将 read 正确拆分比对并以弧线标记跳过的内含子区间。\n\nSplice-aware 比对工具通过两类策略处理跨剪接位点的 reads：\n\n**策略一：外显子图谱索引（HISAT2）**：在构建基因组索引时，将已知的剪接位点信息编码进图结构索引，比对时直接在图上搜索最优路径，既能利用先验知识，又支持发现新剪接位点。\n\n**策略二：种子-延伸（STAR）**：先将 read 的各段子序列分别映射到基因组，识别出可能的剪接位点，再将片段在剪接位点处拼合。\n\n---\n\n## STAR 与 HISAT2：两大主流 Splice-Aware 比对工具\n\nSTAR 和 HISAT2 是目前 bulk RNA-seq 流程中最常用的两款 splice-aware 比对工具，均能处理跨剪接位点的 reads，但在算法设计、资源消耗与适用场景上存在显著差异。\n\n### 核心差异对比\n\n| 维度 | STAR | HISAT2 |\n|---|---|---|\n| **算法** | 后缀数组（Suffix Array）+ 种子拼接 | 图基因组（Graph Genome）+ BWT-FM 索引 |\n| **索引内存** | ~30 GB（人类基因组） | ~4 GB（人类基因组） |\n| **比对速度** | 极快（~50M reads/分钟） | 较快（~30M reads/分钟） |\n| **剪接位点发现** | 2-pass 模式，新位点发现能力强 | 依赖预建图索引，已知位点准确率高 |\n| **SNP/单倍型感知** | 不支持 | 支持（`grch38_snp_tran` 索引） |\n| **输出** | BAM + SJ.out.tab（剪接位点表） | BAM（无内建剪接位点表） |\n| **主要下游用途** | featureCounts、DESeq2、新转录本发现 | featureCounts、DESeq2、变异感知比对 |\n| **推荐场景** | 服务器环境；需发现新剪接位点；大队列分析 | 内存受限环境（≤8 GB）；SNP感知比对 |\n\n:::note\n**如何选择：** 若服务器内存充足（≥32 GB），优先选用 STAR，因其 2-pass 模式在新剪接位点检测上具有明显优势，且是 ENCODE 流程的官方标准。若在笔记本或内存受限（<16 GB）的环境下教学演示，HISAT2 是更实用的替代方案——本课程提供了预建的 `grch38_snp_tran` 索引，可直接使用。\n:::\n\n### HISAT2 完整 Workflow\n\n本地已有预建 HISAT2 索引（`grch38_snp_tran`，含 SNP 和已知转录本信息），可直接跳过索引构建步骤。教学演示使用根目录下的 1M 子集文件；实际分析请改用 `data/trimmed/` 下的 trim 后全量文件。\n\n```bash\n# ── Environment: rnaseq-env (conda activate rnaseq-env) ──────────────────────\nBASE=\"/Users/angdong/Documents/bio_example/bulkRNA\"\nHISAT2_INDEX=\"${BASE}/ref/grch38_snp_tran/genome_snp_tran\"\nGTF=\"${BASE}/ref/GRCh38.109.gtf\"\nRESULTS_DIR=\"${BASE}/results/hisat2\"\n\n# PE samples with 1M teaching subsets available at ${BASE}/\nPE_SAMPLES=\"SRR1039508 SRR1039512 SRR1039516\"\n\n# === Step 1: Align paired-end reads ===\n# --dta : optimise output for featureCounts / StringTie\n# No --rna-strandness flag: airway dataset is unstranded (infer_experiment.py confirmed ~0.5/0.5)\n# Align stats are captured from stderr to *_align_stats.txt\n\nfor SAMPLE in ${PE_SAMPLES}; do\n  mkdir -p ${RESULTS_DIR}/${SAMPLE}\n  hisat2 \\\n    -p 8 \\\n    --dta \\\n    -x ${HISAT2_INDEX} \\\n    -1 ${BASE}/${SAMPLE}_1_1M.fastq.gz \\\n    -2 ${BASE}/${SAMPLE}_2_1M.fastq.gz \\\n    -S ${RESULTS_DIR}/${SAMPLE}/${SAMPLE}.sam \\\n    2> ${RESULTS_DIR}/${SAMPLE}/${SAMPLE}_align_stats.txt\n\n  # === Step 2: SAM → sorted BAM → index (remove intermediate SAM) ===\n  samtools sort -@ 8 \\\n    -o ${RESULTS_DIR}/${SAMPLE}/${SAMPLE}.sorted.bam \\\n    ${RESULTS_DIR}/${SAMPLE}/${SAMPLE}.sam\n  samtools index ${RESULTS_DIR}/${SAMPLE}/${SAMPLE}.sorted.bam\n  rm ${RESULTS_DIR}/${SAMPLE}/${SAMPLE}.sam\ndone\n\n# === Step 3: Count reads with featureCounts ===\n# -s 0 : unstranded (airway dataset uses Illumina TruSeq non-stranded kit)\nfeatureCounts \\\n  -T 8 \\\n  -a ${GTF} \\\n  -o ${RESULTS_DIR}/hisat2_counts.txt \\\n  -s 0 -p -B -C \\\n  --countReadPairs \\\n  ${RESULTS_DIR}/SRR1039508/SRR1039508.sorted.bam \\\n  ${RESULTS_DIR}/SRR1039512/SRR1039512.sorted.bam \\\n  ${RESULTS_DIR}/SRR1039516/SRR1039516.sorted.bam\n```\n\n:::tip\n**查看 HISAT2 比对统计：** 上方命令已将 stderr 重定向至 `*_align_stats.txt`，格式示例如下：\n\n```bash\ncat ${BASE}/results/hisat2/SRR1039508/SRR1039508_align_stats.txt\n# 1000000 reads; of these:\n#   1000000 (100.00%) were paired; of these:\n#       51121 (5.11%) aligned concordantly 0 times\n#      909646 (90.96%) aligned concordantly exactly 1 time\n#       39233 (3.92%) aligned concordantly >1 times\n# 97.07% overall alignment rate\n```\n\n生产环境（全量数据）只需将输入替换为 trim 后文件：\n```bash\n-1 ${BASE}/data/trimmed/${SAMPLE}_1.fastq.gz \\\n-2 ${BASE}/data/trimmed/${SAMPLE}_2.fastq.gz \\\n```\n:::\n\n---\n\n## STAR：RNA-seq 比对的工业标准\n\nSTAR（Spliced Transcripts Alignment to a Reference）是目前使用最广泛的 RNA-seq 比对工具，兼顾速度（基于 RAM 的高速索引）与准确性（支持 2-pass 模式发现新剪接位点）。\n\n### STAR 比对算法原理\n\nSTAR 的比对分为两个核心阶段：\n\n**第一阶段：种子查找（Maximal Mappable Prefix, MMP）**\n\nSTAR 从 read 的每个位置出发，在基因组索引中寻找能精确匹配的最长前缀序列（MMP）。这一步利用了后缀数组（Suffix Array）索引实现高速查找。对于一个跨越剪接位点的 read，MMP 会在第一个外显子末端停止延伸，产生一个\"未映射尾部\"。\n\n**第二阶段：拼接与比对评分**\n\n对每个 MMP 片段，STAR 在其末端的基因组区域内搜索可能的剪接信号（GT-AG 规则，GT…AG 是内含子两端的保守序列），将未映射的尾部延伸至下一个外显子起始位置，验证拼合后的比对得分。得分最高的比对方案即为最终结果。\n\n:::note\n**两遍比对（2-pass mode）：** STAR 的第一遍比对（1-pass）利用注释中的已知剪接位点；在第一遍完成后，将发现的所有新剪接位点加入索引，再进行第二遍比对（2-pass）。这显著提高了低表达基因的新剪接位点检出率，推荐在正式分析中开启（`--twopassMode Basic`）。\n:::\n\n### GTF 注释文件的作用\n\nGTF（General Transfer Format）文件描述基因组注释，是 STAR 索引构建和 featureCounts 计数的必要输入。理解其层级结构有助于正确设置工具参数。\n\n```\n# GTF 文件结构示例（第9列含关键属性）\n# chr  source  feature  start     end    .  strand  .  attributes\nchr1  ENSEMBL  gene     65419     71585  .  +  .  gene_id \"ENSG00000186092\"; gene_name \"OR4F5\";\nchr1  ENSEMBL  transcript 65419  71585  .  +  .  gene_id \"ENSG00000186092\"; transcript_id \"ENST00000641515\";\nchr1  ENSEMBL  exon     65419     65433  .  +  .  gene_id \"ENSG00000186092\"; transcript_id \"ENST00000641515\";\nchr1  ENSEMBL  exon     65520     65573  .  +  .  gene_id \"ENSG00000186092\"; transcript_id \"ENST00000641515\";\n```\n\n关键层级：`gene` → `transcript` → `exon`。featureCounts 在 `exon` 级别计数，通过 `gene_id` 属性将结果汇总至基因层面。\n\n### STAR 索引构建与比对\n\n基因组 FASTA 文件已存在于本地，可直接进行索引构建，无需下载。\n\n```bash\n# ── Environment: star-env (conda activate star-env) ──────────────────────────\nBASE=\"/Users/angdong/Documents/bio_example/bulkRNA\"\nGENOME_DIR=\"${BASE}/ref\"\nSTAR_INDEX=\"${GENOME_DIR}/star_index\"   # dir exists; index not yet built\n\n# === Step 1: Build STAR genome index ===\n# Requires ~30 GB RAM; --sjdbOverhang = read length - 1 (150 bp reads → 149)\n# genome FASTA already at: ${GENOME_DIR}/Homo_sapiens.GRCh38.dna.primary_assembly.fa\nSTAR \\\n  --runMode genomeGenerate \\\n  --genomeDir ${STAR_INDEX} \\\n  --genomeFastaFiles ${GENOME_DIR}/Homo_sapiens.GRCh38.dna.primary_assembly.fa \\\n  --sjdbGTFfile ${GENOME_DIR}/GRCh38.109.gtf \\\n  --sjdbOverhang 149 \\\n  --runThreadN 8\n\n# === Step 2: Align all PE samples (with 2-pass mode) ===\n# Teaching demo uses 1M-read subsets at ${BASE}/\n# For production: replace with ${BASE}/data/trimmed/${SAMPLE}_[12].fastq.gz\nRESULTS_DIR=\"${BASE}/results/star\"\nPE_SAMPLES=\"SRR1039508 SRR1039512 SRR1039516\"\n\nfor SAMPLE in ${PE_SAMPLES}; do\n  mkdir -p ${RESULTS_DIR}/${SAMPLE}\n  STAR \\\n    --runThreadN 8 \\\n    --genomeDir ${STAR_INDEX} \\\n    --readFilesIn \\\n      ${BASE}/${SAMPLE}_1_1M.fastq.gz \\\n      ${BASE}/${SAMPLE}_2_1M.fastq.gz \\\n    --readFilesCommand zcat \\\n    --outSAMtype BAM SortedByCoordinate \\\n    --outSAMattributes NH HI AS NM MD \\\n    --outFileNamePrefix ${RESULTS_DIR}/${SAMPLE}/ \\\n    --outFilterType BySJout \\\n    --alignSJoverhangMin 8 \\\n    --alignSJDBoverhangMin 1 \\\n    --outFilterMismatchNmax 999 \\\n    --outFilterMismatchNoverReadLmax 0.04 \\\n    --alignIntronMin 20 \\\n    --alignIntronMax 1000000 \\\n    --alignMatesGapMax 1000000 \\\n    --twopassMode Basic\n  samtools index ${RESULTS_DIR}/${SAMPLE}/Aligned.sortedByCoord.out.bam\ndone\n\n# Key STAR output files per sample:\n# Aligned.sortedByCoord.out.bam  -- sorted, indexed BAM\n# Log.final.out                  -- alignment summary statistics\n# SJ.out.tab                     -- discovered splice junction table\n```\n\n**STAR Log.final.out 关键指标解读**：\n\n```\n# Good alignment results (expected ranges):\nUniquely mapped reads %       |  80-95%   (< 75% may indicate quality issues)\n% of reads mapped to multiple loci  |  5-15%   (high in repetitive regions)\n% of reads unmapped: too short |  < 5%    (high suggests over-trimming)\n```\n\n---\n\n## 表达量定量：两种主流策略\n\n@fig-quant-strategies 对比了两种策略的核心流程差异：**比对后计数**（Alignment-based counting）先将 reads 全基因组比对再逐外显子计数，**伪比对定量**（Pseudo-alignment）跳过全基因组比对、直接通过 k-mer 索引将 reads 映射到转录本并估计丰度。\n\n\n::: {.cell}\n::: {.cell-output-display}\n![两种主流表达量定量策略流程对比。左侧为比对后计数策略（featureCounts），右侧为伪比对定量策略（Salmon）。箭头代表数据流向，色块代表关键处理步骤。](transcriptomics_basic_lesson2_files/figure-html/fig-quant-strategies-1.png){#fig-quant-strategies width=1056}\n:::\n:::\n\n\n### 策略一：比对后计数（featureCounts）\n\nfeatureCounts 是 Subread 工具包的组成部分，逐个统计每个基因的外显子区域内的比对 reads 数量。其优点是流程直观、结果可解释性强；缺点是对多比对 reads 的处理较为简单，且不估计转录本层面的不确定性。\n\n```bash\n# featureCounts: count reads per gene (using exon features)\n# -s 0 = unstranded (airway dataset, confirmed by infer_experiment.py)\n# -p   = paired-end mode\n# -B   = both mates must be mapped\n# -C   = exclude chimeric reads\n\nfeatureCounts \\\n  -T 16 \\\n  -a Homo_sapiens.GRCh38.109.gtf \\\n  -o results/featureCounts/airway_counts.txt \\\n  -s 0 \\\n  -p -B -C \\\n  --countReadPairs \\\n  results/star/SRR1039508/Aligned.sortedByCoord.out.bam \\\n  results/star/SRR1039512/Aligned.sortedByCoord.out.bam \\\n  results/star/SRR1039516/Aligned.sortedByCoord.out.bam\n\n# featureCounts output: tab-delimited matrix\n# Rows = genes (Ensembl ID), Columns = samples\n# First 6 columns: GeneID, Chr, Start, End, Strand, Length\n```\n\n**重叠歧义处理**：当一个 read 跨越两个基因的外显子时，featureCounts 默认丢弃该 read（`--fracOverlap 0`）。对于重叠基因密集的区域，可使用 `--fraction` 参数将 read 计数按重叠比例分配，但这会产生非整数计数，不适用于 DESeq2。\n\n### 策略二：伪比对定量（Salmon）\n\nSalmon 采用了完全不同的范式：**不进行全基因组比对**，而是将 reads 与**转录本序列**进行快速匹配（quasi-mapping），利用 k-mer 哈希索引定位读段到最可能的转录本。这种方式在速度上快 10–50 倍，同时内置了多种偏差校正模型。\n\n:::info\n**黄金法则：** Salmon 内置的 GC 偏差校正（`--gcBias`）和序列偏差校正（`--seqBias`）在大多数真实 RNA-seq 数据上能提高定量精度，特别是对 GC 含量极端的基因。建议默认开启两者。\n:::\n\n```bash\n# === Step 1: Build Salmon index from transcript sequences ===\n# Extract transcript sequences from genome + GTF using gffread\ngffread Homo_sapiens.GRCh38.109.gtf \\\n  -g Homo_sapiens.GRCh38.dna.primary_assembly.fa \\\n  -w transcripts.fa\n\n# Build Salmon index (with decoy-aware indexing for higher accuracy)\n# The decoy file is the genome itself (for selective alignment)\ngrep \"^>\" Homo_sapiens.GRCh38.dna.primary_assembly.fa | \\\n  cut -d \" \" -f 1 | sed 's/>//' > decoys.txt\n\ncat transcripts.fa Homo_sapiens.GRCh38.dna.primary_assembly.fa > gentrome.fa\n\nsalmon index \\\n  --transcripts gentrome.fa \\\n  --decoys decoys.txt \\\n  --index index/salmon_GRCh38 \\\n  --gencode \\\n  --threads 16\n\n# === Step 2: Quantify each sample ===\n# --libType A = auto-detect library type\n# --gcBias    = correct for GC content bias\n# --seqBias   = correct for sequence-specific bias\n# --validateMappings = use selective alignment (recommended)\n\nsalmon quant \\\n  --index index/salmon_GRCh38 \\\n  --libType A \\\n  --mates1 data/trimmed/SRR1039508_1.fastq.gz \\\n  --mates2 data/trimmed/SRR1039508_2.fastq.gz \\\n  --output results/salmon/SRR1039508 \\\n  --gcBias \\\n  --seqBias \\\n  --validateMappings \\\n  --threads 16\n\n# Output: results/salmon/SRR1039508/quant.sf\n# Columns: Name (transcript ID), Length, EffectiveLength, TPM, NumReads\n```\n\n**理解选择性比对（Selective Alignment）**：常规 Salmon 的 quasi-mapping 速度极快，但可能将来自类似序列的 reads 错误分配。Selective Alignment（`--validateMappings`）引入了一个额外验证步骤：对候选转录本执行完整的序列比对打分，显著减少了假阳性映射，在准确性上接近 STAR 全基因组比对，而速度仍比 STAR 快 3–5 倍。\n\n### 使用 tximport 汇总 Salmon 结果\n\nSalmon 在转录本层面进行定量，而下游分析（DESeq2）通常在基因层面进行。tximport 包负责将转录本级别的 TPM 和 counts 汇总至基因层面，同时传递 Salmon 的不确定性估计（Bootstrap 分位数），为 DESeq2 提供更可靠的输入。\n\n```r\nlibrary(tximport)\nlibrary(DESeq2)\n\n# Create transcript-to-gene mapping table\n# Using biomaRt or pre-downloaded tx2gene file\nlibrary(biomaRt)\nmart <- useMart(\"ensembl\", dataset = \"hsapiens_gene_ensembl\")\ntx2gene <- getBM(\n  attributes = c(\"ensembl_transcript_id_version\", \"ensembl_gene_id\"),\n  mart = mart\n)\n# Save for reuse\nwrite.csv(tx2gene, \"tx2gene_GRCh38.csv\", row.names = FALSE)\n\n# Define sample paths\nsample_ids <- c(\"SRR1039508\", \"SRR1039512\", \"SRR1039516\",\n                \"SRR1039509\", \"SRR1039513\", \"SRR1039517\")\nfiles <- file.path(\"results/salmon\", sample_ids, \"quant.sf\")\nnames(files) <- sample_ids\n\n# Import and summarize to gene level\ntxi <- tximport(\n  files,\n  type = \"salmon\",\n  tx2gene = tx2gene,\n  ignoreTxVersion = TRUE   # strip version numbers from transcript IDs\n)\n\n# txi is a list with: counts, abundance (TPM), length, countsFromAbundance\n# Use txi$counts for DESeq2 input (scaled to gene-level counts)\ndim(txi$counts)   # genes x samples matrix\n```\n\n---\n\n## 定量单位的选择：TPM、FPKM 与原始计数\n\n### 各单位的计算公式\n\n三种常见定量单位针对不同的偏差进行校正：\n\n**FPKM（Fragments Per Kilobase of transcript per Million mapped reads）**：\n$$\\text{FPKM}_i = \\frac{C_i}{L_i / 10^3 \\times N / 10^6} = \\frac{C_i \\times 10^9}{L_i \\times N}$$\n\n其中 $C_i$ 是基因 $i$ 的 read 数，$L_i$ 是基因有效长度（bp），$N$ 是样本的总 mapped reads 数。同时校正基因长度和测序深度。\n\n**TPM（Transcripts Per Million）**：\n$$\\text{TPM}_i = \\frac{C_i / L_i}{\\sum_j (C_j / L_j)} \\times 10^6$$\n\n先对每个基因做长度校正，再将所有基因的 TPM 归一化使总和为 10^6。**TPM 的关键优势**：同一样本中所有基因的 TPM 之和恒为 10^6，使不同样本间同一基因的 TPM 可以直接比较（FPKM 无此性质）。\n\n**原始计数（Raw Counts）**：featureCounts 或 tximport 输出的未经归一化整数计数，仅校正了测序深度差异（由 DESeq2 的 Size Factor 在分析过程中处理）。\n\n### 为什么 DESeq2 必须使用原始计数？\n\nDESeq2 的负二项分布统计模型要求输入**未归一化的整数计数**，原因如下：\n\n1. **模型假设**：负二项分布模拟的是测序过程中随机抽样的计数数据；TPM/FPKM 是连续值且不服从此分布；\n2. **内部归一化**：DESeq2 通过 Size Factor 在模型内部处理测序深度差异，外部归一化会破坏模型的统计假设；\n3. **方差估计**：DESeq2 的过离散度（Overdispersion）估计依赖于计数数据的整数性质。\n\n:::warning\n**严重错误提示：** 将 TPM 或 FPKM 值输入 DESeq2 是一个严重的统计错误，会导致假阳性率失控。正确的做法是：DESeq2 和 edgeR 使用原始计数；跨样本可视化和基因水平比较使用 TPM；FPKM 已基本被 TPM 取代，不推荐使用。\n:::\n\n---\n\n## 两种定量策略的比较\n\n| 特性 | featureCounts | Salmon |\n|---|---|---|\n| 比对方式 | 基于全基因组 BAM 比对 | 伪比对/选择性比对 |\n| 速度 | 较慢（依赖 STAR 输出） | 极快（直接从 FASTQ） |\n| 偏差校正 | 无 | GC bias、序列偏差 |\n| 多比对处理 | 默认丢弃；`-M --fraction` 分数分配 | EM 算法优化分配 |\n| 不确定性估计 | 无 | Bootstrap 区间 |\n| 输出层级 | 基因级别 | 转录本级别（需 tximport） |\n| DESeq2 兼容性 | 直接兼容 | 需通过 tximport |\n| 推荐场景 | 快速分析、已有 BAM 文件 | 新项目、需要偏差校正 |\n\n### 多比对 reads 的处理策略\n\n当一条 read 能比对到基因组多个位置时，称为**多比对 read（multimapper）**。多比对现象在上表中是两种策略最核心的行为差异之一，理解其来源和处理逻辑有助于正确解读定量结果。\n\n多比对的主要来源：\n\n- **重复元件**：LINE、SINE、转座子家族中高度相似的拷贝；\n- **同源基因家族**：如组蛋白基因簇、嗅觉受体基因家族；\n- **假基因**：与功能基因高度相似但无功能的序列拷贝。\n\n不同工具的处理策略及适用场景：\n\n| 工具与参数 | 策略 | 适用场景 |\n|---|---|---|\n| STAR（默认输出） | 保留所有比对位置，`NH:i:N` 标记总数 | 保留原始信息，由下游工具决策 |\n| featureCounts（默认） | 丢弃全部多比对 reads | 保守计数；DESeq2 首选 |\n| featureCounts `-M --fraction` | 按位置数均等分配（产生小数计数） | 估计总体趋势；**不适用于 DESeq2** |\n| Salmon | EM 算法迭代优化，按转录本丰度加权分配 | 转录本级别定量的最优策略 |\n\n:::warning\n**`--fraction` 产生的小数计数不可用于 DESeq2：** DESeq2 的负二项分布模型要求严格整数输入。若使用 `-M --fraction`，须在导入前先取整（`round()`），但这会引入额外误差，不推荐用于差异表达分析。\n:::\n\n```bash\n# 查看 STAR 输出的多比对率\nBASE=\"/Users/angdong/Documents/bio_example/bulkRNA\"\ngrep \"% of reads mapped to multiple loci\" \\\n  ${BASE}/results/star/SRR1039508/Log.final.out\n\n# 统计唯一比对 vs 全部比对 reads（STAR 中 MAPQ=255 表示唯一比对）\nsamtools view -c -q 255 \\\n  ${BASE}/results/hisat2/SRR1039508/SRR1039508.sorted.bam   # uniquely mapped\nsamtools view -c -F 4 \\\n  ${BASE}/results/hisat2/SRR1039508/SRR1039508.sorted.bam   # all mapped\n```\n\n---\n\n## 实践：完整比对与定量流程\n\n以下脚本将前述各步骤串联为完整流程，以本地教学数据集中三个配对末端样本（1M 子集）为例。\n\n```bash\n# ── Environment: star-env for alignment; rnaseq-env for featureCounts ────────\nBASE=\"/Users/angdong/Documents/bio_example/bulkRNA\"\nSTAR_INDEX=\"${BASE}/ref/star_index\"\nGTF=\"${BASE}/ref/GRCh38.109.gtf\"\nSTAR_OUT=\"${BASE}/results/star\"\nFC_OUT=\"${BASE}/results/featureCounts\"\nPE_SAMPLES=\"SRR1039508 SRR1039512 SRR1039516\"\n\nmkdir -p ${FC_OUT}\n\n# === Step 1: STAR alignment (conda activate star-env) ===\nfor SAMPLE in ${PE_SAMPLES}; do\n  mkdir -p ${STAR_OUT}/${SAMPLE}\n  STAR \\\n    --runThreadN 8 \\\n    --genomeDir ${STAR_INDEX} \\\n    --readFilesIn \\\n      ${BASE}/${SAMPLE}_1_1M.fastq.gz \\\n      ${BASE}/${SAMPLE}_2_1M.fastq.gz \\\n    --readFilesCommand zcat \\\n    --outSAMtype BAM SortedByCoordinate \\\n    --outSAMattributes NH HI AS NM MD \\\n    --outFileNamePrefix ${STAR_OUT}/${SAMPLE}/ \\\n    --outFilterType BySJout \\\n    --alignSJoverhangMin 8 \\\n    --alignSJDBoverhangMin 1 \\\n    --outFilterMismatchNmax 999 \\\n    --outFilterMismatchNoverReadLmax 0.04 \\\n    --alignIntronMin 20 \\\n    --alignIntronMax 1000000 \\\n    --alignMatesGapMax 1000000 \\\n    --twopassMode Basic\n  samtools index ${STAR_OUT}/${SAMPLE}/Aligned.sortedByCoord.out.bam\ndone\n\n# === Step 2: featureCounts on all BAM files (conda activate rnaseq-env) ===\n# -s 0 = unstranded (airway dataset)\nfeatureCounts \\\n  -T 8 \\\n  -a ${GTF} \\\n  -o ${FC_OUT}/airway_counts.txt \\\n  -s 0 -p -B -C --countReadPairs \\\n  ${STAR_OUT}/SRR1039508/Aligned.sortedByCoord.out.bam \\\n  ${STAR_OUT}/SRR1039512/Aligned.sortedByCoord.out.bam \\\n  ${STAR_OUT}/SRR1039516/Aligned.sortedByCoord.out.bam\n```\n\n```r\n# === R: Compare featureCounts vs Salmon quantification ===\nlibrary(tximport)\nlibrary(readr)\nlibrary(ggplot2)\n\n# Load featureCounts output\nfc_data <- read.table(\n  \"results/featureCounts/airway_counts.txt\",\n  header = TRUE, skip = 1, row.names = 1\n)\nfc_counts <- fc_data[, 7:ncol(fc_data)]\ncolnames(fc_counts) <- c(\"SRR1039508\", \"SRR1039512\", \"SRR1039516\")\n\n# Load Salmon via tximport\ntx2gene <- read.csv(\"tx2gene_GRCh38.csv\")\nfiles <- file.path(\"results/salmon\",\n                   c(\"SRR1039508\", \"SRR1039512\", \"SRR1039516\"),\n                   \"quant.sf\")\nnames(files) <- c(\"SRR1039508\", \"SRR1039512\", \"SRR1039516\")\ntxi <- tximport(files, type = \"salmon\",\n                tx2gene = tx2gene, ignoreTxVersion = TRUE)\n\n# Align gene IDs and compute correlation\ncommon_genes <- intersect(rownames(fc_counts), rownames(txi$counts))\nfc_s1 <- fc_counts[common_genes, \"SRR1039508\"]\nsalmon_s1 <- txi$counts[common_genes, \"SRR1039508\"]\n\ncor_val <- cor(log1p(fc_s1), log1p(salmon_s1))\n\n# Scatter plot comparison\ndf_compare <- data.frame(\n  featureCounts = log1p(fc_s1),\n  Salmon        = log1p(salmon_s1)\n)\n\nggplot(df_compare, aes(x = featureCounts, y = Salmon)) +\n  geom_point(alpha = 0.2, size = 0.5, color = \"steelblue\") +\n  geom_abline(slope = 1, intercept = 0,\n              color = \"firebrick\", linetype = \"dashed\") +\n  annotate(\"text\", x = 2, y = 12,\n           label = sprintf(\"Pearson r = %.4f\", cor_val),\n           size = 4) +\n  labs(\n    x = \"log1p(featureCounts)\",\n    y = \"log1p(Salmon)\",\n    title = \"featureCounts vs Salmon: SRR1039508\",\n    subtitle = \"Each point = one gene; diagonal = perfect agreement\"\n  ) +\n  theme_classic()\n```\n\n---\n\n## SAM/BAM 格式解析\n\n理解比对输出文件的格式，是排查比对问题和下游分析的基础。STAR 和 HISAT2 均输出 SAM（Sequence Alignment/Map）格式或其二进制压缩版 BAM。\n\n### SAM 文件结构\n\nSAM 文件由两部分组成：以 `@` 开头的**头部（Header）**行，以及每条 read 的**比对记录**行（11 个强制字段 + 可选标签）。\n\n```bash\n# View BAM file header\nsamtools view -H sample.bam | head -20\n\n# View first 5 alignment records\nsamtools view sample.bam | head -5\n\n# Example alignment record:\n# QNAME   FLAG  RNAME  POS    MAPQ  CIGAR    RNEXT  PNEXT  TLEN  SEQ   QUAL\n# SRR...1   99   chr1  65419   255  90M60N60M  =    65560   201  ACGT..  IIII..\n```\n\n**关键字段解读**：\n\n**FLAG（比对标志位）**：16 位整数，每位代表一个属性。常用位：\n\n| 值 | 含义 |\n|---|---|\n| 1 (0x1) | 双端测序读段 |\n| 4 (0x4) | 该 read 未比对 |\n| 16 (0x10) | 比对在反链 |\n| 64 (0x40) | Read 1 |\n| 128 (0x80) | Read 2 |\n\n一条 FLAG = 99 的 read 含义：99 = 64+32+2+1，即双端读段（1）、配对正确（2）、配对 read 在反链（32）、本 read 是 Read 1（64）。\n\n**CIGAR 字符串**：描述 read 如何与参考序列对齐：\n\n| 符号 | 含义 |\n|---|---|\n| M | 匹配（含错配） |\n| N | 跳跃（对应内含子） |\n| S | 软截断（read 末端未比对，序列保留） |\n| I | 插入 |\n| D | 缺失 |\n\n例如 `90M2000N60M` 表示：read 前 90 bp 比对到外显子，跳过 2000 bp 内含子，后 60 bp 比对到下一个外显子——这是一条典型的 junction read。\n\n```bash\n# Useful samtools commands for QC\n# Check alignment statistics\nsamtools flagstat sample.bam\n\n# Check per-chromosome mapping rates\nsamtools idxstats sample.bam\n\n# View only uniquely mapped reads (MAPQ >= 255 for STAR)\nsamtools view -q 255 sample.bam | head -5\n\n# Check insert size distribution (for paired-end data)\nsamtools stats sample.bam | grep \"^IS\" | \\\n  awk '{print $2, $3}' > insert_sizes.txt\n```\n\n---\n\n## 定量结果的质量诊断\n\nfeatureCounts 完成基因计数后，仅凭原始计数矩阵尚无法判断定量质量。系统性地检查比对片段的分配状态、基因检出率及样本间一致性，是进入差异表达分析前不可省略的一步。本节基于对三个 1M-read 教学子集（SRR1039508、SRR1039512、SRR1039516）运行 featureCounts 后生成的 `hisat2_counts.txt` 及其 `.summary` 文件，演示完整的定量质控流程。\n\n### 步骤一：解析 featureCounts Summary\n\nfeatureCounts 为每个输入 BAM 文件生成独立的 `.summary` 文件，记录每类 reads 的分配去向。\n\n```bash\n# View the featureCounts summary file\ncat /Users/angdong/Documents/bio_example/bulkRNA/results/hisat2/hisat2_counts.txt.summary\n```\n\n实际输出如下：\n\n```\nStatus                  SRR1039508      SRR1039512      SRR1039516\nAssigned                816310          820960          812201\nUnassigned_Unmapped      14326           5067            7012\nUnassigned_Singleton     34688          45925           48926\nUnassigned_Chimera        6609           6514            5335\nUnassigned_MultiMapping 135125         110519          120739\nUnassigned_NoFeatures    37025          38851           40577\nUnassigned_Ambiguity     59100          55640           56770\n```\n\n计算各样本的 reads 分配率：\n\n```bash\n# Calculate assignment rate for each sample\nawk 'NR==1{next}\n/^Assigned/{a[1]=$2; a[2]=$3; a[3]=$4}\n{for(i=2;i<=NF;i++) t[i-1]+=$i}\nEND{\n  for(i=1;i<=3;i++)\n    printf \"Sample %d: Assigned=%d / Total=%d = %.1f%%\\n\", i, a[i], t[i], a[i]/t[i]*100\n}' /Users/angdong/Documents/bio_example/bulkRNA/results/hisat2/hisat2_counts.txt.summary\n```\n\n```\nSample 1 (SRR1039508): Assigned=816310 / Total=1103183 = 74.0%\nSample 2 (SRR1039512): Assigned=820960 / Total=1083476 = 75.8%\nSample 3 (SRR1039516): Assigned=812201 / Total=1091560 = 74.4%\n```\n\n:::note\n**合格阈值参考**\n\n一般而言，poly-A 富集 RNA-seq 的 featureCounts 分配率应达到 **70–85%**，低于 60% 则需深入排查原因。本数据集三个样本均在 74–76% 之间，在使用 1M-read 教学子集（覆盖度较低）的前提下，属于正常范围。\n:::\n\n### 步骤二：解读未分配 reads 的成因\n\n未分配 reads 按类别具有不同的生物学与技术含义，准确区分它们是排除系统误差的关键。\n\n| 未分配类别 | SRR1039508 | SRR1039512 | SRR1039516 | 主要原因 |\n|---|---|---|---|---|\n| MultiMapping | 135,125 (12.3%) | 110,519 (10.2%) | 120,739 (11.1%) | reads 比对到基因组多个位置，来自重复元件、旁系同源基因等 |\n| Ambiguity | 59,100 (5.4%) | 55,640 (5.1%) | 56,770 (5.2%) | reads 同时重叠两个或以上基因注释区域 |\n| NoFeatures | 37,025 (3.4%) | 38,851 (3.6%) | 40,577 (3.7%) | reads 落在注释基因组区域之外（内含子、基因间区等） |\n| Singleton | 34,688 (3.1%) | 45,925 (4.2%) | 48,926 (4.5%) | 配对末端中只有一端比对成功 |\n| Chimera | 6,609 (0.6%) | 6,514 (0.6%) | 5,335 (0.5%) | 两端比对到不同染色体或方向矛盾 |\n| Unmapped | 14,326 (1.3%) | 5,067 (0.5%) | 7,012 (0.6%) | 比对步骤中未映射到参考基因组 |\n\n**MultiMapping（10–12%）**是本数据集最大的未分配来源。这一比例在人类 poly-A RNA-seq 中属于正常水平：人类基因组含有大量基因家族和假基因，短读长（75 bp）片段难以区分其来源。featureCounts 默认丢弃多比对 reads（可通过 `-M` 参数保留，但通常不推荐用于 DEA）。\n\n**Ambiguity（~5%）**反映了基因注释的重叠程度。GRCh38 Ensembl release 109 包含大量互相重叠的转录本，5% 左右的歧义率属于预期范围。\n\n**Singleton（3–4.5%）**比例在三个样本中差异相对较大（SRR1039508 最低 3.1%，SRR1039516 最高 4.5%），提示这两个样本在比对时 R1/R2 有效片段配对率略有差异，但不影响后续分析。\n\n:::tip\n**排查高 NoFeatures 比例的思路**\n\n若 `Unassigned_NoFeatures` 超过 20%，应优先检查：(1) GTF 与 BAM 的基因组版本是否一致（GRCh37 vs GRCh38）；(2) GTF 的染色体命名格式（`chr1` vs `1`）是否与 BAM header 一致；(3) 文库是否为非 poly-A，导致大量内含子 reads。本数据集 NoFeatures 仅 3–4%，可排除上述问题。\n:::\n\n### 步骤三：统计基因检出数量\n\n分配率衡量 reads 层面的效率，而基因检出数量则反映转录组的覆盖广度。\n\n```bash\n# Count total genes, all-zero genes, and detected genes\nawk 'NR>2{\n  genes++;\n  if($7==0 && $8==0 && $9==0) zero++;\n  else expressed++;\n} END{\n  printf \"Total annotated genes : %d\\n\", genes;\n  printf \"All-zero genes        : %d (%.1f%%)\\n\", zero, zero/genes*100;\n  printf \"Detected (count>=1)   : %d (%.1f%%)\\n\", expressed, expressed/genes*100;\n}' /Users/angdong/Documents/bio_example/bulkRNA/results/hisat2/hisat2_counts.txt\n```\n\n```\nTotal annotated genes : 62710\nAll-zero genes        : 44929 (71.6%)\nDetected (count>=1)   : 17781 (28.4%)\n```\n\nGTF 中注释了 62,710 个基因，但仅有约 17,781 个（28.4%）在至少一个样本中获得 ≥1 个计数。这一结果看似比例偏低，实则正常：\n\n1. **1M-read 子集覆盖度有限**：完整数据（~25M reads/样本）通常可检出 15,000–20,000 个基因；1M-read 仅覆盖最高表达的转录本，低表达基因计数为 0 是预期结果。\n2. **细胞类型特异性**：airway 平滑肌细胞并非万能细胞，大量神经特异性、免疫特异性基因在该细胞类型中不表达。\n3. **GTF 注释冗余**：Ensembl GTF 包含大量假基因（pseudogene）、lncRNA 及预测基因，真正在 mRNA-seq 中活跃转录的编码基因约 15,000–18,000 个，与检出数量吻合。\n\n:::tip\n**低表达基因过滤建议**\n\n进入差异表达分析（DEA）前，通常需要过滤掉极低表达的基因以提高统计检验的可靠性。推荐标准：在至少 `n` 个样本中计数 ≥10（`n` 等于最小组别的样本数）。例如，本 3 样本数据集可使用：\n\n```r\ndds_filtered <- dds[rowSums(counts(dds) >= 10) >= 2, ]\n```\n\n过滤后保留基因数通常在 10,000–15,000 之间。\n:::\n\n### 步骤四：与 airway 官方计数的相关性验证\n\nreads 分配率衡量的是流程层面的效率，而定量结果的准确性需要通过与可信参考进行比对来验证。`airway` Bioconductor 包收录了 Himes et al.（2014）发表时配套的基因级计数矩阵，该矩阵基于完整数据（~25M reads/样本）使用 HTSeq 生成，可作为金标准参照。将本教学流程产出的 1M-read 子集计数（HISAT2 + featureCounts）与同一样本的官方计数进行 Pearson 相关分析，能够直接回答：**在仅使用 1/25 数据量的情况下，手动搭建的流程能否重现官方定量结果？**\n\n三个教学子集样本（SRR1039508、SRR1039512、SRR1039516）均存在于 `airway` 包中，可直接提取对应列进行比对。\n\n```r\nlibrary(airway)\nlibrary(SummarizedExperiment)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(tidyr)\n\n# ── 1. Load official airway counts (full dataset, HTSeq) ──────────────────────\ndata(airway)\nairway_counts <- assay(airway, \"counts\")              # matrix: genes × 8 samples\n# Column names use SRA run IDs; select the 3 matching samples\ntarget_samples <- c(\"SRR1039508\", \"SRR1039512\", \"SRR1039516\")\nairway_sub <- airway_counts[, target_samples]         # genes × 3\n\n# ── 2. Load manual featureCounts output (1M-read subset) ─────────────────────\nfc_raw <- read.table(\n  \"/Users/angdong/Documents/bio_example/bulkRNA/results/hisat2/hisat2_counts.txt\",\n  header = TRUE, skip = 1, row.names = 1\n)\nfc_mat <- as.matrix(fc_raw[, 6:8])\ncolnames(fc_mat) <- target_samples\n\n# ── 3. Align gene sets: keep genes present in both matrices ───────────────────\ncommon_genes <- intersect(rownames(airway_sub), rownames(fc_mat))\nairway_common <- airway_sub[common_genes, ]\nfc_common     <- fc_mat[common_genes, ]\n\n# Keep only genes with count >= 1 in at least one source to remove double-zero noise\nany_expr <- rowSums(airway_common) > 0 | rowSums(fc_common) > 0\nairway_common <- airway_common[any_expr, ]\nfc_common     <- fc_common[any_expr, ]\n\ncat(\"Genes in common:\", nrow(airway_common), \"\\n\")\n\n# ── 4. Log2(count + 1) transformation ────────────────────────────────────────\nlog_airway <- log2(airway_common + 1)\nlog_fc     <- log2(fc_common + 1)\n\n# ── 5. Per-sample Pearson correlation ─────────────────────────────────────────\nr_vals <- sapply(target_samples, function(s)\n  cor(log_airway[, s], log_fc[, s], method = \"pearson\")\n)\nprint(round(r_vals, 4))\n\n# ── 6. Scatter plot: manual (1M) vs official (full) for each sample ───────────\ndf_scatter <- lapply(target_samples, function(s) {\n  data.frame(\n    gene      = rownames(log_airway),\n    official  = log_airway[, s],\n    manual_1M = log_fc[, s],\n    sample    = s,\n    condition = ifelse(s %in% c(\"SRR1039508\", \"SRR1039516\"),\n                       \"dexamethasone\", \"untreated\")\n  )\n}) |> bind_rows()\n\nr_labels <- data.frame(\n  sample    = target_samples,\n  condition = c(\"dexamethasone\", \"untreated\", \"dexamethasone\"),\n  label     = paste0(\"r = \", round(r_vals, 4))\n)\n\nggplot(df_scatter, aes(x = official, y = manual_1M, color = condition)) +\n  geom_point(alpha = 0.10, size = 0.5) +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\",\n              color = \"grey40\", linewidth = 0.6) +\n  geom_text(data = r_labels,\n            aes(x = 1, y = 14, label = label),\n            inherit.aes = FALSE, hjust = 0, size = 4) +\n  scale_color_manual(values = c(dexamethasone = \"#E41A1C\",\n                                untreated     = \"#377EB8\")) +\n  facet_wrap(~sample, nrow = 1) +\n  labs(\n    x     = \"log2(count + 1)  —  airway official (full reads)\",\n    y     = \"log2(count + 1)  —  manual pipeline (1M-read subset)\",\n    title = \"Manual quantification vs airway official counts\",\n    color = \"Condition\"\n  ) +\n  theme_classic(base_size = 12) +\n  theme(strip.background = element_blank(),\n        strip.text = element_text(face = \"bold\"))\n```\n\n**实际结果与解读**\n\n三个样本的 Pearson 相关系数均在 **r ≈ 0.89** 左右，点云整体位于对角线**下方**。这一结果在预期之内，可从以下两个相互独立的原因加以解释。\n\n**原因一：1M-read 子集的绝对计数系统性偏低**\n\n本教学流程的输入为每样本约 1M reads，而 `airway` 官方计数基于完整数据（约 25M reads/样本）。绝对计数之比约为 1:25，经 log2 变换后差距约为 $\\log_2(25) \\approx 4.6$，因此点云整体向对角线下方平移约 4–5 个 log2 单位，而非沿对角线分布。低表达基因受影响最为显著：官方计数中有值的基因，在 1M 子集中可能因覆盖度不足而计数为 0，这些点沿 y = 0 横向排布，进一步拉低了整体相关性。\n\n**原因二：注释版本与定量工具差异**\n\n`airway` 包采用 GRCh37（hg19）参考基因组配合 HTSeq 生成计数，而本流程使用 GRCh38（hg38）参考基因组与 featureCounts（Subread v2.1.1）。尽管基因 Ensembl ID 在两个版本间高度一致，但基因边界坐标、外显子结构及重叠处理策略的差异，会导致部分基因的计数结果不完全可比，从而将相关系数压低至 0.89 而非更高。\n\n**综合评估**\n\nr ≈ 0.89 在上述两重系统性差异（数据量 25 倍差距 + 版本与工具不同）的叠加下，说明本教学流程的定量结果与官方发布结果在**表达量排序层面高度一致**，流程本身不存在方向性错误。若使用完整数据（~25M reads）配合相同参考版本（GRCh38 + Ensembl release 109），预期相关系数可提升至 r > 0.95。\n\n:::note\n**为何使用 log2 变换后再计算相关性**\n\n原始计数矩阵中高表达基因（计数可达数万）与低表达基因（计数个位数）之间跨越多个数量级。若直接对原始计数计算 Pearson r，高表达基因将主导相关性，导致 r 虚高（即便低表达区间完全噪声化也能得到 r > 0.99）。log2 变换压缩了数量级差异，使相关系数能更均衡地反映全表达范围内的定量一致性。\n:::\n\n若相关系数低于 0.95，应优先排查：(1) GTF 版本与 `airway` 包使用的注释版本是否匹配（`airway` 基于 GRCh37/hg19，而本流程使用 GRCh38/hg38，基因 ID 应一致但计数会有差异）；(2) featureCounts 的链方向参数（`-s 0`）是否与文库类型一致；(3) 是否误用了完整 FASTQ 而非 1M 子集。\n\n### 定量质控综合评估\n\n基于以上四项检查，本次 featureCounts 定量结果质量良好，具体总结如下：\n\n| 指标 | 本数据结果 | 参考范围 | 评估 |\n|---|---|---|---|\n| reads 分配率 | 74.0–75.8% | ≥70% | 合格 |\n| MultiMapping 比例 | 10.2–12.3% | ≤15% | 正常 |\n| Ambiguity 比例 | 5.1–5.4% | ≤10% | 正常 |\n| NoFeatures 比例 | 3.4–3.7% | ≤10% | 正常 |\n| 检出基因数 | 17,781 | 10K–20K（1M subset）| 符合预期 |\n| 样本间一致性 | 分配率差异 <2% | <5% | 优秀 |\n\n三个样本在所有关键指标上均保持高度一致（分配率差异 <2%），可排除单样本文库制备失败或比对异常的情况。该计数矩阵可直接用于后续的 DESeq2 / edgeR 差异表达分析（参见专题 3）。\n\n---\n\n## 课后自测 (Post-Lesson Quiz)\n\n1. 一个 150 bp 的 RNA-seq read 跨越了一个约 5,000 bp 的内含子：read 的前 90 bp 来自外显子 3，后 60 bp 来自外显子 4。若使用 Bowtie2（非 splice-aware）比对，这条 read 可能会发生什么？使用 STAR 后结果有何不同？\n\n2. STAR 的两遍比对（2-pass mode）与一遍比对相比，主要在哪类 reads 的处理上有优势？其背后的原理是什么？\n\n3. featureCounts 的 `-s` 参数有三个选项（0、1、2）。若对一个 RF-stranded 文库（TruSeq Stranded）使用了 `-s 0`（非链特异性），会对计数结果产生什么影响？\n\n4. 下列哪种情况适合使用 FPKM/TPM，哪种情况必须使用原始计数？\n   - （a）在论文图表中比较同一样本内不同基因的表达水平；\n   - （b）使用 DESeq2 进行差异表达分析；\n   - （c）比较不同物种中同一基因家族的相对表达。\n\n5. Salmon 的 `--gcBias` 校正对哪类基因的定量影响最大？请说明原因。\n\n<details>\n<summary><strong>参考答案 (Reference Answers)</strong></summary>\n\n1. *使用 Bowtie2，该 read 无法被连续比对（中间隔着 5,000 bp 内含子），可能被标记为未比对（unmapped）、或被强制映射到基因组上错误的连续区域（如假基因）。使用 STAR，MMP 算法会在外显子 3 末端识别 GT 剪接信号，将前 90 bp 映射至外显子 3，后 60 bp 映射至外显子 4，正确识别这条 junction read 并计入两个外显子的交界处。*\n\n2. *2-pass 模式主要对低表达基因的新型剪接位点（novel splice junctions）有显著优势。第一遍比对发现的新剪接位点被加入临时索引，第二遍比对时这些新位点能辅助低表达 junction reads 的正确定位——这些 reads 在第一遍中因缺乏索引支持而无法被精确比对，在第二遍中则能利用高表达样本发现的剪接位点信息正确映射。*\n\n3. *使用 `-s 0`（非链特异性），featureCounts 会同时计算正链和反链上的 reads。对于位于正反链都有基因的重叠区域，会引入反义链 reads 的噪声，导致计数虚高；对于无重叠的单基因区域，影响较小。整体效果是增加了假阳性信号，降低了链特异性差异的检测能力。*\n\n4. *（a）可视化同一样本内不同基因相对水平 → 使用 TPM（已做长度与深度双校正，同样本内可比）；（b）DESeq2 差异表达 → 必须使用原始计数（整数，满足负二项模型假设）；（c）跨物种比较 → 使用 TPM（深度和长度已校正），但需注意基因长度在不同物种间可能不同，应谨慎解读。*\n\n5. *GC 偏差校正对 GC 含量极端的基因影响最大——即 GC 含量极高（> 70%）或极低（< 30%）的基因。这些基因在 PCR 扩增过程中效率不同（GC 富集区域扩增效率低），导致它们的 reads 数量系统性偏低或偏高。Salmon 的 GC bias 校正通过对每个基因按其 GC 含量估计一个校正因子，补偿这一系统性偏差。*\n\n</details>\n",
    "supporting": [
      "transcriptomics_basic_lesson2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}